### PR TITLE
Wrong unknown stockStatusLevel

### LINKED ISSUE #33: wrong stockStatusLevel 'unknown'
When there are no understocked products and one of the products is unknown (ex.: tt)

### PR DESCRIPTION
**Pull request by patriciagarcia**
Closes #33 

Connects https://github.com/fielded/nav-integrated-national-dashboard/issues/306

### CODE REVIEW

File: dist/bundle.js [hunk 1]
```diff
@@ -208,17 +212,17 @@
         };
 
         var addStockLevelStatusField = function addStockLevelStatusField(stockCount) {
-          var unknownProducts = productsGroupedByStatus(stockCount.stock).unknown.length;
-          var understockedProducts = productsGroupedByStatus(stockCount.stock).understock.length;
+          var grouped = productsGroupedByStatus(stockCount.stock, products);
+          var understockedProducts = grouped.understock.length;
+          var totalGrouped = understockedProducts + grouped['re-stock'].length + grouped.overstock.length + grouped.ok.length;
```
Comment (jjal) [inline dist/bundle.js]: This seems somewhat fragile

**Review by jjal — CHANGES_REQUESTED** [review]
Minor comment on using summing using explicit statuses - adding a status level is unlikely but this'd be hard to find if it happened.

**Review by jjal — APPROVED** [review]
